### ISSUE TITLE
Current master not compatible with blue.ilpdemo.org

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp#81]
When you try to run the psk sample code from the readme against two accounts on blue.ilpdemo.org, it fails:

```sh
request: { address: 'de.eur.blue.jam.~psk.2ZQkTFtiMyM.Ox38P-XneFqfW8fUGJ_Upw.fe467539-e88f-4bcc-a109-286206d3efac',
  amount: '10',
  expires_at: '2017-03-15T13:44:36.870Z',
  condition: '5F7iWFAzXazcEqzDRRT2S2d2w4ZtdmY5AWhzKmTMmvw' }
paymentParams { sourceAmount: '10',
  connectorAccount: undefined,
  destinationAmount: '10',
  destinationAccount: 'de.eur.blue.jam.~psk.2ZQkTFtiMyM.Ox38P-XneFqfW8fUGJ_Upw.fe467539-e88f-4bcc-a109-286206d3efac',
  destinationMemo: { data: undefined, expires_at: '2017-03-15T13:44:36.870Z' },
  expiresAt: '2017-03-15T13:44:19.178Z',
  executionCondition: '5F7iWFAzXazcEqzDRRT2S2d2w4ZtdmY5AWhzKmTMmvw' }
{ InvalidFieldsError: Body did not match schema Transfer
    at InvalidFieldsError (/Users/michiel/gh/interledgerjs/ilp/node_modules/ilp-plugin-bells/src/errors/index.js:5:5)
    at FiveBellsLedger._sendTransfer (/Users/michiel/gh/interledgerjs/ilp/node_modules/ilp-plugin-bells/src/lib/plugin.js:526:49)
    at next (native)
    at onFulfilled (/Users/michiel/gh/interledgerjs/ilp/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7) name: 'InvalidFieldsError' }
```

This is related to https://github.com/interledgerjs/ilp-plugin-bells/issues/111

**Comment by emschwartz** [comment]
That is expected. ILP Kit is still using older components. We were planning to make breaking changes to the components because of the change to simple conditions and the new ILP packet format but we didn't want to break the community network twice in quick succession. The ILP Kit will be updated for the latest components in V2 (see the [milestone](https://github.com/interledgerjs/ilp-kit/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0))

**Comment by michielbdejong** [comment]
ok, but it would be good to mention this in the readme. It is easily fixed with this patch, by the way: https://github.com/interledgerjs/ilp/commit/ef0b1ec6cba323c5226bd83097928ca08ffcf384
